engines:
  rubocop:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - "**.rb"
  - "bin/*"
exclude_paths:
- spec/**/*
